apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: visa-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1  # Start with 1 replica
  maxReplicas: 2  # Scale up to maximum 2 replicas under load
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75  # Scale when CPU > 75%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85  # Scale when memory > 85%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120  # Wait 2 min before scaling up
      policies:
      - type: Pods
        value: 1  # Add max 1 pod at a time
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      policies:
      - type: Pods
        value: 1  # Remove max 1 pod at a time
        periodSeconds: 120