apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: visa-app
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: visa-app
data:
  init.sql: |
    -- Database initialization script
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    
    -- Create tables if they don't exist
    CREATE TABLE IF NOT EXISTS visa_bulletins (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        bulletin_date DATE NOT NULL,
        category VARCHAR(10) NOT NULL,
        country VARCHAR(50) NOT NULL,
        priority_date DATE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE INDEX IF NOT EXISTS idx_visa_bulletins_date ON visa_bulletins(bulletin_date);
    CREATE INDEX IF NOT EXISTS idx_visa_bulletins_category ON visa_bulletins(category);
    CREATE INDEX IF NOT EXISTS idx_visa_bulletins_country ON visa_bulletins(country);